CC="g++"
PROJECT=FILTERS
SRC=filters.cpp
LIBS=pkg-config --cflags --libs opencv`

$(PROJECT) : $(SRC)
	$(CC) $(SRC) -o $(PROJECT) $(LIBS)


 g++ filters.cpp -o filter -std=c++11 `pkg-config --cflags --libs opencv4`

	